/*
 * Generated by Bluespec Compiler, version 2024.07-22-g934465e3 (build 934465e3)
 * 
 * On Tue Feb 25 13:39:40 EST 2025
 * 
 */
#include "bluesim_primitives.h"
#include "mk_fifo_example.h"


/* Constructor */
MOD_mk_fifo_example::MOD_mk_fifo_example(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_fifo_1(simHdl, "fifo_1", this, 32u, 2u, (tUInt8)1u, 0u),
    INST_fifo_2(simHdl, "fifo_2", this, 32u, 2u, (tUInt8)1u, 0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 2u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mk_fifo_example::init_symbols_0()
{
  init_symbol(&symbols[0u], "fifo_1", SYM_MODULE, &INST_fifo_1);
  init_symbol(&symbols[1u], "fifo_2", SYM_MODULE, &INST_fifo_2);
}


/* Rule actions */


/* Methods */

void MOD_mk_fifo_example::METH_put_data(tUInt32 ARG_put_data_a, tUInt32 ARG_put_data_b)
{
  INST_fifo_1.METH_enq(ARG_put_data_a);
  INST_fifo_2.METH_enq(ARG_put_data_b);
}

tUInt8 MOD_mk_fifo_example::METH_RDY_put_data()
{
  tUInt8 DEF_CAN_FIRE_put_data;
  tUInt8 PORT_RDY_put_data;
  DEF_CAN_FIRE_put_data = INST_fifo_1.METH_i_notFull() && INST_fifo_2.METH_i_notFull();
  PORT_RDY_put_data = DEF_CAN_FIRE_put_data;
  return PORT_RDY_put_data;
}

tUInt64 MOD_mk_fifo_example::METH_get_data()
{
  tUInt32 DEF_fifo_1_first____d3;
  tUInt32 DEF_fifo_2_first____d4;
  tUInt64 PORT_get_data;
  DEF_fifo_2_first____d4 = INST_fifo_2.METH_first();
  DEF_fifo_1_first____d3 = INST_fifo_1.METH_first();
  PORT_get_data = (((tUInt64)(DEF_fifo_1_first____d3)) << 32u) | (tUInt64)(DEF_fifo_2_first____d4);
  INST_fifo_1.METH_deq();
  INST_fifo_2.METH_deq();
  return PORT_get_data;
}

tUInt8 MOD_mk_fifo_example::METH_RDY_get_data()
{
  tUInt8 DEF_CAN_FIRE_get_data;
  tUInt8 PORT_RDY_get_data;
  DEF_CAN_FIRE_get_data = INST_fifo_1.METH_i_notEmpty() && INST_fifo_2.METH_i_notEmpty();
  PORT_RDY_get_data = DEF_CAN_FIRE_get_data;
  return PORT_RDY_get_data;
}


/* Reset routines */

void MOD_mk_fifo_example::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_fifo_2.reset_RST(ARG_rst_in);
  INST_fifo_1.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mk_fifo_example::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mk_fifo_example::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_fifo_1.dump_state(indent + 2u);
  INST_fifo_2.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mk_fifo_example::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 3u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  num = INST_fifo_1.dump_VCD_defs(num);
  num = INST_fifo_2.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mk_fifo_example::dump_VCD(tVCDDumpType dt,
				   unsigned int levels,
				   MOD_mk_fifo_example &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mk_fifo_example::vcd_defs(tVCDDumpType dt, MOD_mk_fifo_example &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
    }
}

void MOD_mk_fifo_example::vcd_prims(tVCDDumpType dt, MOD_mk_fifo_example &backing)
{
  INST_fifo_1.dump_VCD(dt, backing.INST_fifo_1);
  INST_fifo_2.dump_VCD(dt, backing.INST_fifo_2);
}
