/*
 * Generated by Bluespec Compiler, version 2024.07-22-g934465e3 (build 934465e3)
 * 
 * On Tue Feb 25 13:39:40 EST 2025
 * 
 */

/* Generation options: */
#ifndef __mk_fifo_example_h__
#define __mk_fifo_example_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mk_fifo_example module */
class MOD_mk_fifo_example : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Fifo<tUInt32> INST_fifo_1;
  MOD_Fifo<tUInt32> INST_fifo_2;
 
 /* Constructor */
 public:
  MOD_mk_fifo_example(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_put_data(tUInt32 ARG_put_data_a, tUInt32 ARG_put_data_b);
  tUInt8 METH_RDY_put_data();
  tUInt64 METH_get_data();
  tUInt8 METH_RDY_get_data();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mk_fifo_example &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mk_fifo_example &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mk_fifo_example &backing);
};

#endif /* ifndef __mk_fifo_example_h__ */
