/*
 * Generated by Bluespec Compiler, version 2024.07-22-g934465e3 (build 934465e3)
 * 
 * On Fri Feb  7 15:27:13 EST 2025
 * 
 */

/* Generation options: */
#ifndef __mk_counter_h__
#define __mk_counter_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mk_counter module */
class MOD_mk_counter : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_rg_count;
  MOD_Wire<tUInt32> INST_wr_decr;
  MOD_Wire<tUInt32> INST_wr_incr;
 
 /* Constructor */
 public:
  MOD_mk_counter(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt32 DEF_signed_rg_count___d3;
  tUInt32 DEF_b__h238;
 
 /* Rules */
 public:
  void RL_rl_incr();
  void RL_rl_decr();
 
 /* Methods */
 public:
  void METH_ma_start(tUInt8 ARG_ma_start_count_up);
  tUInt8 METH_RDY_ma_start();
  tUInt32 METH_ma_stop();
  tUInt8 METH_RDY_ma_stop();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mk_counter &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mk_counter &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mk_counter &backing);
};

#endif /* ifndef __mk_counter_h__ */
