/*
 * Generated by Bluespec Compiler, version 2024.07-22-g934465e3 (build 934465e3)
 * 
 * On Fri Feb  7 15:27:13 EST 2025
 * 
 */
#include "bluesim_primitives.h"
#include "mk_counter_Tb.h"


/* String declarations */
static std::string const __str_literal_3("TB:                    done", 27u);
static std::string const __str_literal_2("TB:           count down", 24u);
static std::string const __str_literal_1("TB: count up", 12u);


/* Constructor */
MOD_mk_counter_Tb::MOD_mk_counter_Tb(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_count(simHdl, "count", this),
    INST_rg_counter_tb(simHdl, "rg_counter_tb", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 6u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mk_counter_Tb::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h115", SYM_DEF, &DEF_b__h115, 32u);
  init_symbol(&symbols[1u], "count", SYM_MODULE, &INST_count);
  init_symbol(&symbols[2u], "RL_rl_decrement", SYM_RULE);
  init_symbol(&symbols[3u], "RL_rl_finish", SYM_RULE);
  init_symbol(&symbols[4u], "RL_rl_start_count", SYM_RULE);
  init_symbol(&symbols[5u], "rg_counter_tb", SYM_MODULE, &INST_rg_counter_tb);
}


/* Rule actions */

void MOD_mk_counter_Tb::RL_rl_start_count()
{
  DEF_b__h115 = INST_rg_counter_tb.METH_read();
  DEF_rg_counter_tb_PLUS_1___d3 = DEF_b__h115 + 1u;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_1);
  INST_count.METH_ma_start((tUInt8)1u);
  INST_rg_counter_tb.METH_write(DEF_rg_counter_tb_PLUS_1___d3);
}

void MOD_mk_counter_Tb::RL_rl_decrement()
{
  DEF_b__h115 = INST_rg_counter_tb.METH_read();
  DEF_rg_counter_tb_PLUS_1___d3 = DEF_b__h115 + 1u;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_2);
  INST_count.METH_ma_start((tUInt8)0u);
  INST_rg_counter_tb.METH_write(DEF_rg_counter_tb_PLUS_1___d3);
}

void MOD_mk_counter_Tb::RL_rl_finish()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_3);
  INST_rg_counter_tb.METH_write(0u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_finish(sim_hdl, "32", 1u);
}


/* Methods */


/* Reset routines */

void MOD_mk_counter_Tb::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_rg_counter_tb.reset_RST(ARG_rst_in);
  INST_count.reset_RST_N(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mk_counter_Tb::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mk_counter_Tb::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_count.dump_state(indent + 2u);
  INST_rg_counter_tb.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mk_counter_Tb::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 4u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h115", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "rg_counter_tb_PLUS_1___d3", 32u);
  num = INST_rg_counter_tb.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_count.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mk_counter_Tb::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mk_counter_Tb &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mk_counter_Tb::vcd_defs(tVCDDumpType dt, MOD_mk_counter_Tb &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_b__h115) != DEF_b__h115)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h115, 32u);
	backing.DEF_b__h115 = DEF_b__h115;
      }
      ++num;
      if ((backing.DEF_rg_counter_tb_PLUS_1___d3) != DEF_rg_counter_tb_PLUS_1___d3)
      {
	vcd_write_val(sim_hdl, num, DEF_rg_counter_tb_PLUS_1___d3, 32u);
	backing.DEF_rg_counter_tb_PLUS_1___d3 = DEF_rg_counter_tb_PLUS_1___d3;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_b__h115, 32u);
      backing.DEF_b__h115 = DEF_b__h115;
      vcd_write_val(sim_hdl, num++, DEF_rg_counter_tb_PLUS_1___d3, 32u);
      backing.DEF_rg_counter_tb_PLUS_1___d3 = DEF_rg_counter_tb_PLUS_1___d3;
    }
}

void MOD_mk_counter_Tb::vcd_prims(tVCDDumpType dt, MOD_mk_counter_Tb &backing)
{
  INST_rg_counter_tb.dump_VCD(dt, backing.INST_rg_counter_tb);
}

void MOD_mk_counter_Tb::vcd_submodules(tVCDDumpType dt,
				       unsigned int levels,
				       MOD_mk_counter_Tb &backing)
{
  INST_count.dump_VCD(dt, levels, backing.INST_count);
}
