/*
 * Generated by Bluespec Compiler, version 2024.07-22-g934465e3 (build 934465e3)
 * 
 * On Wed Feb  5 20:12:58 EST 2025
 * 
 */

/* Generation options: */
#ifndef __mkModuleDeepThought_h__
#define __mkModuleDeepThought_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkModuleDeepThought module */
class MOD_mkModuleDeepThought : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_a;
  MOD_Reg<tUInt32> INST_b;
  MOD_Reg<tUInt32> INST_c;
  MOD_Reg<tUInt32> INST_d;
 
 /* Constructor */
 public:
  MOD_mkModuleDeepThought(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt32 DEF_signed_c___d6;
  tUInt32 DEF_b__h202;
  tUInt32 DEF_signed_a___d2;
  tUInt32 DEF_b__h196;
  tUInt32 DEF_signed_b___d4;
  tUInt32 DEF_b__h199;
 
 /* Rules */
 public:
  void RL_compute_answer();
 
 /* Methods */
 public:
  void METH_the_assign(tUInt32 ARG_the_assign_x, tUInt32 ARG_the_assign_y, tUInt32 ARG_the_assign_z);
  tUInt8 METH_RDY_the_assign();
  tUInt32 METH_the_answer();
  tUInt8 METH_RDY_the_answer();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkModuleDeepThought &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkModuleDeepThought &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkModuleDeepThought &backing);
};

#endif /* ifndef __mkModuleDeepThought_h__ */
