//
// Generated by Bluespec Compiler, version 2024.07-22-g934465e3 (build 934465e3)
//
// On Sat Feb  1 13:14:47 EST 2025
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 unused
// RST_N                          I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_greet, WILL_FIRE_RL_greet;

  // rule RL_greet
  assign CAN_FIRE_RL_greet = 1'd1 ;
  assign WILL_FIRE_RL_greet = 1'd1 ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    $display(" Hello World - From Vignesh ! ");
    $finish(32'd1);
  end
  // synopsys translate_on
endmodule  // mkTb

